[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 1
[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
baseURL = 'https://hugo.poc.bytesbyboon.be/'
languageCode = 'en-us'
title = 'My New Hugo Site'
[caches]
    [caches.images]
        dir = ':cacheDir/images'
